apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f ../docker-compose/docker-compose.yml
    kompose.version: 1.21.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: cola-mutuas
  name: cola-mutuas
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: cola-mutuas
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f ../docker-compose/docker-compose.yml
        kompose.version: 1.21.0 ()
      creationTimestamp: null
      labels:
        io.kompose.service: cola-mutuas
    spec:
      containers:
      - env:
        - name: RABBITMQ_DEFAULT_PASS
          value: admin
        - name: RABBITMQ_DEFAULT_USER
          value: admin
        image: rabbitmq:management
        imagePullPolicy: ""
        name: cola-mutuas
        resources: {}
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
status: {}
