apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f ../docker-compose/docker-compose.yml
    kompose.service.type: LoadBalancer
    kompose.version: 1.20.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: producer
  name: producer
spec:
  replicas: 2
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f ../docker-compose/docker-compose.yml
        kompose.service.type: LoadBalancer
        kompose.version: 1.20.0 ()
      creationTimestamp: null
      labels:
        io.kompose.service: producer
    spec:
      containers:
      - image: spring-integration-rabbitmq-producer-demo:0.0.1-SNAPSHOT
        name: producer
        ports:
        - containerPort: 8080
        resources: {}
      restartPolicy: Always
status: {}
